#!/bin/bash

NIV() {

tput setaf 2
command cat << 'EOF'

Total chapters in each book 

Gen:50   Job:42   Hab:3    Col:4
Exod:40  Ps:150   Zeph:3   1Thess:5
Lev:27   Prov:31  Hag:2    2Thess:3
Num:36   Eccl:12  Zech:14  1Tim:6
Deut:34  Song:8   Mal:4    2Tim:4
Josh:24  Isa:66   Matt:28  Titus:3
Judg:21  Jer:52   Mark:16  Phlm:1
Ruth:4   Lam:5    Luke:24  Heb:13
1Sam:31  Ezek:48  John:21  Jas:5
2Sam:24  Dan:12   Acts:28  1Pet:5
1Kgs:22  Hos:14   Rom:16   2Pet:3
2Kgs:25  Joel:3   1Cor:16  1John:5
1Chr:29  Amos:9   2Cor:13  2John:1
2Chr:36  Obad:1   Gal:6    3John:1
Ezra:10  Jonah:4  Eph:6    Jude:1
Neh:13   Mic:7    Phil:4   Rev:22
Esth:10  Nah:3
EOF

tput setaf 208
command cat << 'EOF'

Provided by NIV Dramatized Audio Bible © 2011 by Zondervan. https://www.zondervan.com/
https://www.biblegateway.com/ The Bible in multiple languages, versions, and formats
EOF

tput setaf 5
printf "%b\n"
printf "%b\n" "Type book and chapter you want to listen to.
Example		Rom 7"

tput setaf 14
read -r -p "Book & Chapter
  " line
book=$(printf "%s" "${line}" | awk '{print $1}')
chapter=$(printf "%s" "${line}" | awk '{print $2}')
tput cuu 27
tput el1
tput ed
tput cnorm
tput setaf 2
printf "%b\n"
printf "%b\n" "P for Pause & Play     Left, Right, Up, Down Arrows for Fwd & Rev"
printf "%b\n\n"
tput setaf 4
printf "%b\n" "While playing type ctrl-Z then type bg to backgroud the process and continue
listening while still working in the terminal. To get back type fg to foreground the process\n\n\n"
tput cnorm
tput sgr0
curl -s https://www.biblegateway.com/audio/dramatized/niv/${book}.${chapter} | grep -Eo 'https.*ogg' | xargs mpv
}

if [ $# -eq 0 ]
  then
    NIV
    
elif [ $# -eq 2 ]
then
book=${1}
chapter=${2}
tput setaf 2
printf "%b\n"
printf "%b\n" "---------------------------------------------------------------------------------------------\n"
printf "%b\n" "P for Pause & Play     Left, Right, Up, Down Arrows for Fwd & Rev"
printf "%b\n\n"
tput setaf 4
printf "%b\n" "While playing type ctrl-Z then type bg to backgroud the process and continue
listening while still working in the terminal. To get back type fg to foreground the process\n"
printf "%b\n" "---------------------------------------------------------------------------------------------\n"
tput cnorm
tput sgr0
curl -s https://www.biblegateway.com/audio/dramatized/niv/${book}.${chapter} | grep -Eo 'https.*ogg' | xargs mpv
  
  elif [ ! $# -eq 0 ] || [ ! $# -eq 2 ]
  then
    printf "%b\n" "Script requires either 0 or 2 arguments"
fi
